#
# Copyright (c) 2021 Tero Koskinen, Michael Rohan
# SPDX-License-Identifier: ISC
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

# Alire (https://alire.ada.dev/) - Ada Library Package Manager definition
# for Ahven.

name = "ahven"
version = "2.9.0"
description = "Unit Testing Library for Ada Programming Language"
website = "http://ahven.stronglytyped.org/"
licenses = "ISC"
authors = ["Tero Koskinen <tero.koskinen@iki.fi>"]

# The maintainer of the Alire configuration is Michael Rohan.  All other
# code is by Tero.
maintainers = ["Michael Rohan <mrohan@zanyblue.com>"]
maintainers-logins = ["mkrohan"]

project-files = ["gnat/ahven_alire.gpr"]

# The AHVEN_OS environment variable is used select the OS implementation
# directory in the project file.
[gpr-externals]
AHVEN_OS = ["windows", "unix"]

[gpr-set-externals."case(os)"]
windows = { AHVEN_OS = "windows" }
"..."   = { AHVEN_OS = "unix" }
